/*
	File: setWeaponBench.sqf
	Author: moeck

*/
private _tentSpawnPosition = player modelToWorld[0,5,0];//player modelToWorld[0,5,0];
private _tentdir = 0;
player playMoveNow "AinvPknlMstpSnonWnonDnon_medic_1";
sleep 2;
	_tent = createVehicle ["Land_MedicalTent_01_white_generic_outer_F", _tentSpawnPosition, [] ,0, "CAN_COLLIDE"];
	_tent setDir _tentDir;
	_tent setVectorUp (surfaceNormal _tentSpawnPosition);
	_tent enableSimulation false;
	_tent allowDamage false;
	_tent setDir (getDir player);
	_tent setpos (player modelToWorld[0,5,0]);
sleep 2;
	//Workbench 1
	_workbench1pos= _tent modelToWorld[-3.2,-1.5,-1.4];
	_workbench1 = createvehicle ["Land_WoodenTable_large_F", _workbench1pos, [] , 0, "CAN_COLLIDE"];
	_workbench1 setVectorDirAndUp [(vectorDir _tent),(vectorUp _tent)];
	_workbench1 attachTo [_tent];
	_workbench1 addaction [localize ("STR_Process_Rifle"),life_fnc_processActionSingle,"rifle",0,false,false,"",' life_inv_waffenbody_p > 0 && life_inv_holz_p > 0 &&!life_is_processing && !life_action_inUse'];
	_workbench1 addaction [localize ("STR_Process_Pistol"),life_fnc_processActionSingle,"pistol",0,false,false,"",' life_inv_waffenbody_p > 0 && life_inv_plastik_p > 0 &&!life_is_processing && !life_action_inUse'];
sleep 2;
	_weaponbox1pos = _workbench1 modelToWorld[-0.05,-0.5,0.42];
	_weaponbox1 = createVehicle ["Land_Ammobox_rounds_F", _weaponbox1pos , [] , 0, "CAN_COLLIDE"]; 
	_weaponbox1 setDir ((getDir _workbench1)+45);
	_weaponbox1 enableSimulation false;
	_weaponbox1 allowDamage false;
	_weaponbox1 setDamage 1;
	_weaponbox1 attachTo [_workbench1];
	_workbench1 enableSimulation false;
sleep 1;
	_workbench2pos= _tent modelToWorld[-3.2,1.6,-1.4];
	_workbench2 = createvehicle ["Land_WoodenTable_large_F", _workbench2pos, [] , 0, "CAN_COLLIDE"];
	_workbench2 setVectorDirAndUp [(vectorDir _tent),(vectorUp _tent)];
	_workbench2 setDir (getDir _tent);
	_workbench2 attachTo [_tent];
	_workbench2 addaction [localize ("STR_Process_Rifle"),life_fnc_processActionSingle,"rifle",0,false,false,"",' life_inv_waffenbody_p > 0 && life_inv_holz_p > 0 &&!life_is_processing && !life_action_inUse'];
	_workbench2 addaction [localize ("STR_Process_Pistol"),life_fnc_processActionSingle,"pistol",0,false,false,"",' life_inv_waffenbody_p > 0 && life_inv_plastik_p > 0 &&!life_is_processing && !life_action_inUse'];
player playMoveNow "AinvPknlMstpSnonWnonDnon_medic_1";
sleep 1;
	_metalwirepos = _workbench2 modelToWorld[0.2,0.1,0.42];
	_metalwire = createvehicle ["Land_MetalWire_F", _metalwirepos, [] , 0, "CAN_COLLIDE"];
	_metalwire enableSimulation false;
	_metalwire attachTo [_workbench2];
sleep 2;
	//Laptop
	_laptoppos = _workbench2 modelToWorld[-0.3,-0.4,0.42];
	_laptop = createvehicle ["Land_Tablet_02_F", _laptoppos, [] , 0, "CAN_COLLIDE"];
	_laptop setDir ((getDir _workbench2) - 90);
	_laptop enableSimulation false;
	_laptop attachTo [_workbench2];
sleep 2;
	_ammoboxpos = _workbench2 modelToWorld[-0.3,0.7,0.42];
	_ammobox=createVehicle ["Land_Ammobox_rounds_F", _ammoboxpos, [] ,0, "CAN_COLLIDE"];
	_ammobox setDir ((getDir _workbench2)+ 105);
	_ammobox enableSimulation false;
	_ammobox setDamage 1;
	_ammobox attachTo [_workbench2];
sleep 1;
	_mag1pos = _workbench2 modelToWorld[0.05,0.65,0.42];
	_mag1 = createVehicle ["Land_Magazine_rifle_F", _mag1pos, [] ,0, "CAN_COLLIDE"];
	_mag1 setDir ((getDir _workbench2) +105);
	_mag2pos = _workbench2 modelToWorld[0.15,0.78,0.42];
	_mag2 = createVehicle ["Land_Magazine_rifle_F", _mag2pos, [] ,0, "CAN_COLLIDE"];
	_mag2 setDir ((getDir _workbench2) +145);
	_mag3pos = _workbench2 modelToWorld[0.3,0.8,0.42];
	_mag3 = createVehicle ["Land_Magazine_rifle_F", _mag3pos, [] ,0, "CAN_COLLIDE"];
	_mag3 setDir (getDir _workbench2);
	_mag4pos = _workbench2 modelToWorld[0.4,0.8,0.42];
	_mag4 = createVehicle ["Land_Magazine_rifle_F", _mag4pos, [] ,0, "CAN_COLLIDE"];
	_mag4 setDir (getDir _workbench2);
	_mag1 enableSimulation false;
	_mag1 setDamage 1;
	_mag2 enableSimulation false;
	_mag2 setDamage 1;
	_mag3 enableSimulation false;
	_mag3 setDamage 1;
	_mag4 enableSimulation false;
	_mag4 setDamage 1;
	_mag1 attachTo [_workbench2];
	_mag2 attachTo [_workbench2];
	_mag3 attachTo [_workbench2];
	_mag4 attachTo [_workbench2];
sleep 1;
player playMoveNow "AinvPknlMstpSnonWnonDnon_medic_1";
sleep 1;
	//Pallete
	_mil_pallet_boxpos= _tent modelToWorld[-3.2,-4.1,-1.4];
	_mil_pallet_box = createvehicle ["Land_Pallet_MilBoxes_F", _mil_pallet_boxpos , [] , 0, "CAN_COLLIDE"];
	_mil_pallet_box enableSimulation false;
	_mil_pallet_box setDamage 1;
	_mil_pallet_box attachTo [_tent];
sleep 2;
	//Dataterminal
	_datatermpos = _tent modelToWorld[-3.4,3.2,-1.4];
	_dataterm = createVehicle ["Land_DataTerminal_01_F", _datatermpos, [] ,0, "CAN_COLLIDE"];
	_dataterm setVectorDirAndUp [(vectorDir _tent),(vectorUp _tent)];
	_dataterm enableSimulation false;
	_dataterm setDamage 1;
	_dataterm attachTo [_tent];
sleep 2;
	//Zielscheibe
	_hostagepos = _tent modelToWorld[-3,4.5,-1.4];
	_hostage = createVehicle ["Hostage_PopUp3_Moving_F", _hostagepos, [] ,0, "CAN_COLLIDE"];
	_hostage setVectorUp (vectorUp _tent);
	_hostage setDir ((getDir _tent) - 15);
	_hostage attachTo [_tent];	
sleep 1;
	//Metallbox
	_metallpos = _tent modelToWorld[3,-4.1,-1.4];
	_metall = createVehicle ["Land_MetalCase_01_large_F", _metallpos, [] ,0, "CAN_COLLIDE"];
	_metall setVectorUp (vectorUp _tent);
	_metall setDir ((getDir _tent) + 15);
	_metall enableSimulation false;
	_metall setDamage 1;
	_metall attachTo [_tent];
sleep 1;
player playMoveNow "AinvPknlMstpSnonWnonDnon_medic_1";
sleep 3;
_cargo1pos = _tent modelToWorld[3,-2,-1.4];
	_cargo1 = createVehicle ["I_CargoNet_01_ammo_F", _cargo1pos, [] ,0, "CAN_COLLIDE"];
	_cargo1 setVectorDirAndUp [(vectorDir _tent),(vectorUp _tent)];
	_cargo1 enableSimulation false;
	_cargo1 setDamage 1;
	_cargo1 attachTo [_tent];	
sleep 3;
	_cargo2pos = _tent modelToWorld[3,0.5,-1.4];
	_cargo2 = createVehicle ["CargoNet_01_box_F", _cargo2pos, [] ,0, "CAN_COLLIDE"];
	_cargo2 setVectorDirAndUp [(vectorDir _tent),(vectorUp _tent)];
	_cargo2 enableSimulation false;
	_cargo2 setDamage 1;
	_cargo2 attachTo [_tent];	
sleep 1;	
player playMoveNow "AinvPknlMstpSnonWnonDnon_medic_1";
sleep 2;
	_cargo3pos = _tent modelToWorld[3,2.8,-1.4];
	_cargo3 = createVehicle ["B_CargoNet_01_ammo_F", _cargo3pos, [] ,0, "CAN_COLLIDE"];
	_cargo3 setVectorDirAndUp [(vectorDir _tent),(vectorUp _tent)];
	_cargo3 enableSimulation false;
	_cargo3 setDamage 1;
	_cargo3 attachTo [_tent];
sleep 3;